### ISSUE TITLE
running the seeds on the Development Setup Guide returns errors

### ISSUE THREAD

**Issue by chivoX** [inaturalist/inaturalist#1275]
https://github.com/inaturalist/inaturalist/wiki/development-setup-guide#create-test-users-places-and-observations

rails r tools/import_us_counties.rb
rails r tools/load_dummy_observations.rb

these two return an error:
```
rails r tools/import_us_counties.rb                                                                                                                                                                  *[master]
/Users/chivoX/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/runner.rb:62:in `<top (required)>': undefined local variable or method `tools' for main:Object (NameError)
        from /Users/chivoX/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/runner.rb:62:in `eval'
        from /Users/chivoX/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/runner.rb:62:in `<top (required)>'
        from /Users/chivoX/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:123:in `require'
        from /Users/chivoX/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
        from /Users/chivoX/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:90:in `runner'
        from /Users/chivoX/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /Users/chivoX/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'

```

**Comment by kueda** [comment]
We don't have the US counties script any more, and you should run these from a shell, not from the Rails terminal.
