### ISSUE TITLE
Error in CSV export

### ISSUE THREAD

**Issue by pleary** [inaturalist/inaturalist#1573]
Delayed job failing to generate this CSV export due to an error `undefined method 'coordinates_viewable_by?' for nil:NilClass` in ProjectObservation:

```delayed_job_id: 488123584 
host: lobaria 
pid: 4427 
process: delayed_job.default_one host:lobaria 
attempts: 2 
unique_hash: 
queue: default 
run_at: 2017-12-13 17:39:37 -0500 
locked_by: delayed_job.default_one host:lobaria pid:4427 
arguments: [#, longitude: #, zoom_level: 3, cover_file_name: nil, cover_content_type: nil, cover_file_size: nil, cover_updated_at: nil, event_url: "", start_time: nil, end_time: nil, trusted: true, group: "", last_aggregated_at: "2017-12-13 21:00:48">, {:path=>"/home/inaturalist/deployment/production/current/tmp/page_cache/observations/project/ebutterfly-north-america.all.csv", :user=>#}] 
model: Observation 
method: generate_csv_for 
model_method: Observation::generate_csv_for 
model_method_id: Observation::generate_csv_for:: 
locked_at: 2017-12-13 17:39:37 -0500 
created_at: 2017-12-13 16:21:55 -0500 
```

```
undefined method `coordinates_viewable_by?' for nil:NilClass
/home/inaturalist/deployment/production/releases/20171213012510/app/models/project_observation.rb:285:in `to_csv_column'
/home/inaturalist/deployment/production/releases/20171213012510/app/models/project.rb:436:in `block (4 levels) in generate_csv'
/home/inaturalist/deployment/production/releases/20171213012510/app/models/project.rb:435:in `map'
/home/inaturalist/deployment/production/releases/20171213012510/app/models/project.rb:435:in `block (3 levels) in generate_csv'
/home/inaturalist/deployment/production/releases/20171213012510/app/models/project.rb:434:in `each'
/home/inaturalist/deployment/production/releases/20171213012510/app/models/project.rb:434:in `block (2 levels) in generate_csv'
/home/inaturalist/deployment/production/shared/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/batches.rb:124:in `find_in_batches'
/home/inaturalist/deployment/production/releases/20171213012510/app/models/projec 
```

**Comment by kueda** [comment]
There are 131 project observations without observations, so that's one part of the problem. Not sure how they get that way though.

**Comment by pleary** [comment]
I just manually delete 262 projects observations with no corresponding observation, with the query:

`DELETE FROM project_observations WHERE id IN (SELECT po.id FROM project_observations po LEFT JOIN observations o ON (po.observation_id=o.id) WHERE o.id IS NULL);`

Odd that its exactly double the number there were in December. I'll close this ticket, and we can reopen if it comes up again
