### ISSUE TITLE
TransactionTooLargeException

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#1810]
https://fabric.io/inaturalist/android/apps/org.inaturalist.android/issues/56329657f5d3a7f76b2daaf1?time=last-seven-days

```
06-08 14:47:49.004 19846-19846/? I/chatty: uid=10271(org.inaturalist.android) identical 1 line
06-08 14:47:52.213 3288-22818/? I/ActivityManager: START u0 {flg=0x24000000 cmp=org.inaturalist.android/.SettingsActivity} from uid 10271
06-08 14:47:52.563 19846-19846/? W/FlurryAgent: Start session with context: org.inaturalist.android.SettingsActivity@1382ad3 count:1
06-08 14:47:52.802 3288-3319/? I/ActivityManager: Displayed org.inaturalist.android/.SettingsActivity: +498ms
06-08 14:47:53.079 19846-19846/? W/FlurryAgent: End session with context: org.inaturalist.android.ObservationListActivity@bf4a50b count:1
06-08 14:47:53.116 19846-19846/? E/AndroidRuntime: FATAL EXCEPTION: main
   Process: org.inaturalist.android, PID: 19846
   java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 2272548 bytes
       at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3950)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
    Caused by: android.os.TransactionTooLargeException: data parcel size 2272548 bytes
       at android.os.BinderProxy.transactNative(Native Method)
       at android.os.BinderProxy.transact(Binder.java:764)
       at android.app.IActivityManager$Stub$Proxy.activityStopped(IActivityManager.java:4623)
       at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3934)
       at android.os.Handler.handleCallback(Handler.java:790) 
       at android.os.Handler.dispatchMessage(Handler.java:99) 
       at android.os.Looper.loop(Looper.java:164) 
       at android.app.ActivityThread.main(ActivityThread.java:6494) 
       at java.lang.reflect.Method.invoke(Native Method) 
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
06-08 14:47:53.126 19846-19846/? W/FlurryAgent: End session with context: org.inaturalist.android.SettingsActivity@1382ad3 count:0
06-08 14:47:53.327 3288-22814/? W/ActivityManager:   Force finishing activity org.inaturalist.android/.SettingsActivity
06-08 14:47:53.339 3288-3311/? I/ActivityManager: Showing crash dialog for package org.inaturalist.android u0
```

Happening for me a lot in build 289, to the point where the app is unusable. Doesn't seem consistent, sometimes happens on obs detail, sometimes on settings, but usually after I've viewed a few screens.

**Comment by kueda** [comment]
Damnit wrong repo.
