### ISSUE TITLE
null check for filterBar

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#2045]
https://fabric.io/inaturalist/android/apps/org.inaturalist.android/issues/5bd65064f8b88c29639bfd9d?time=last-seven-days
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
       at org.inaturalist.android.ExploreActivity.refreshFilterBar(ExploreActivity.java:758)
       at org.inaturalist.android.ExploreActivity.refreshResultsView(ExploreActivity.java:917)
       at org.inaturalist.android.ExploreActivity.refreshViewState(ExploreActivity.java:1245)
       at org.inaturalist.android.ExploreActivity.access$1400(ExploreActivity.java:94)
       at org.inaturalist.android.ExploreActivity$ExplorePagerAdapter.instantiateItem(ExploreActivity.java:1492)
       at android.support.v4.view.ViewPager.addNewItem(ViewPager.java:1004)
       at android.support.v4.view.ViewPager.populate(ViewPager.java:1152)
       at android.support.v4.view.ViewPager.populate(ViewPager.java:1086)
       at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1616)
```

**Comment by kueda** [comment]
Why am I always doing this.
