### ISSUE TITLE
Getting error while loading dummy observations

### ISSUE THREAD

**Issue by jobikjohn** [inaturalist/inaturalist#998]
~/inaturalist/tools$ r load_dummy_observations.rb

```
/home/lastplotdev/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/runner.rb:62:in `<top (required)>': undefined local variable or method `load_dummy_observations' for main:Object (NameError)
	from /home/lastplotdev/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/runner.rb:62:in `eval'
	from /home/lastplotdev/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/runner.rb:62:in `<top (required)>'
	from /home/lastplotdev/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:123:in `require'
	from /home/lastplotdev/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
	from /home/lastplotdev/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:90:in `runner'
	from /home/lastplotdev/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/lastplotdev/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'


```
Please help me to solve it.

**Comment by kueda** [comment]
You want `rails r tools/load_dummr_observations.rb` from the root of the rails repo.

**Comment by jobikjohn** [comment]
I also tried this, but getting error..
```
lastplotdev@lastplotdev:~/inaturalist$ rails r tools/load_dummy_observations.rb   
tools/load_dummy_observations.rb:21:in `block in <top (required)>': undefined method `active?' for nil:NilClass (NoMethodError)
Did you mean?  acts_like?
	from tools/load_dummy_observations.rb:17:in `times'
	from tools/load_dummy_observations.rb:17:in `<top (required)>'
	from /home/lastplotdev/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/runner.rb:60:in `load'
	from /home/lastplotdev/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/runner.rb:60:in `<top (required)>'
	from /home/lastplotdev/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:123:in `require'
	from /home/lastplotdev/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
	from /home/lastplotdev/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:90:in `runner'
	from /home/lastplotdev/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/lastplotdev/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'

```

**Comment by kueda** [comment]
You need to have at least one user in the database for the script to work. I'll add a warning to the script, but that script is really just a convenience tool. You'll probably learn more about how the code works by just poking around and making data manually.
